packages:
  - packages/*
allowBuilds:
  esbuild: true
  protobufjs: false
minimumReleaseAgeExclude:
  - '@evanpurkhiser/*'
  - '@orpc/client@1.15.1'
  - '@orpc/contract@1.15.1'
  - '@orpc/shared@1.15.1'
  - '@orpc/standard-server-fetch@1.15.1'
  - '@orpc/standard-server-peer@1.15.1'
  - '@orpc/standard-server@1.15.1'
  - '@orpc/interop@1.15.1'
  - '@orpc/json-schema@1.15.1'
  - '@orpc/server@1.15.1'
  - '@orpc/standard-server-aws-lambda@1.15.1'
  - '@orpc/standard-server-fastify@1.15.1'
  - '@orpc/standard-server-node@1.15.1'
  - hono@4.13.8
  - '@vitest/mocker@5.0.1'
  - '@vitest/spy@5.0.1'
  - vitest@5.0.1
